// Define action types
export default {
  HANDLE_GET_ORDER_REQUEST: 'HANDLE_GET_ORDER_REQUEST',
  HANDLE_GET_ORDER_SUCCESS: 'HANDLE_GET_ORDER_SUCCESS',
  HANDLE_GET_ORDER_FAILED: 'HANDLE_GET_ORDER_FAILED',
  HANDLE_SELECT_ALTERATION: 'HANDLE_SELECT_ALTERATION',
  HANDLE_SELECT_FITTING_OPTIONS: 'HANDLE_SELECT_FITTING_OPTIONS',
}
